#ifndef EVISOR_ARCH_ARM64_IRQ_VECTORS_LOCAL_DEF_H_
#define EVISOR_ARCH_ARM64_IRQ_VECTORS_LOCAL_DEF_H_

// Allocate stack frame with CPU_CONTEXT_GP_REGS
// See VCpuContext in kernel/sched/sched.h
#define CPU_CONTEXT_GP_REGS 34

#define SYNC_INVALID_SP0_EL2 0
#define IRQ_INVALID_SP0_EL2 1
#define FIQ_INVALID_SP0_EL2 2
#define ERROR_INVALID_SP0_EL2 3

#define SYNC_INVALID_SPX_EL2 4
#define IRQ_INVALID_SPX_EL2 5
#define FIQ_INVALID_SPX_EL2 6
#define ERROR_INVALID_SPX_EL2 7

#define SYNC_INVALID_EL01_64 8
#define IRQ_INVALID_EL01_64 9
#define FIQ_INVALID_EL01_64 10
#define ERROR_INVALID_EL01_64 11

#define SYNC_INVALID_EL01_32 12
#define IRQ_INVALID_EL01_32 13
#define FIQ_INVALID_EL01_32 14
#define ERROR_INVALID_EL01_32 15

#endif  // EVISOR_ARCH_ARM64_IRQ_VECTORS_LOCAL_DEF_H_
